Add observable data service ADR
bitwarden/adr pull request #1
Opened 2022-04-28 14:38 UTC by Hinton

2022-05-10 11:42 UTC, MGibson1 reviewed
I feel we need a PoC branch or PR prior to making a decision on this. I agree that Observables are the preferred way to go _for now_, but decisions from on high without an example to work towards feel destined to failure.

2022-05-12 08:05 UTC, Hinton commented
@MGibson1 Would this suffice as a quick example?

https://github.com/bitwarden/jslib/compare/feature/example-reactive-service
https://github.com/bitwarden/web/compare/feature/example-reactive-data-service

It's not really a "working" example since it doesn't handle account switching but it removes the need to use messages to communicate between two completely different components.

2022-05-12 11:19 UTC, MGibson1 commented
I think that works as a nice call to action that this is better.

I am a little worried about account switching, though. Would we need to have an external hook to update the behavior subject when we load a different account? Maybe the observables don't belong to their respective services, but rather to our god class 😢

2022-05-12 12:50 UTC, Hinton commented
@MGibson1 I envision that the services subscribe to the current account, and perform a state swap at that moment.

Pseudo code
```ts
stateService.account$.subscribe((account) => {
	this._organizations$.next(orgsFromAccoun(account));
}
```

2022-05-12 16:00 UTC, MGibson1 commented
I like that, I think it's worth adding since it would establish that observable on stateService and the correct pattern to adhere to when switching.

Or do you think it'd make things too complicated?

2022-05-30 09:42 UTC, Hinton commented
I added an example to the ADR.

2022-06-01 19:26 UTC, MGibson1 requested changes

2022-06-01 19:26 UTC, MGibson1 commented on decisions/0003-observable-data-services.md
> +At the same time many components are tightly coupled towards the state as well,
This sentence starts in the middle of a thought

2022-06-01 19:26 UTC, MGibson1 commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData<T>: (account: string, key: string, options?: StorageOptions) => Promise<void>;
These should probably be private unless we know they shouldn't be.

At the least I'd like a different account type than `string`. preferrably some kind of `User` or `Account` type

2022-06-03 06:51 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +interface StateService {
Rename to StorageService?

2022-06-03 12:55 UTC, MGibson1 commented on decisions/0004-refactor-state-service.md
> +interface StateService {
That already exists as a lower-level concept. Maybe we could add this interface to the `StorageService`, but I'm not convinced it's wise to merge the ideas of storage with tracking account state.

2022-06-13 13:49 UTC, coroiu commented on decisions/0003-observable-data-services.md
> +  organizations$: Observable<Organization[]> = this._organizations$.asObservable();
Is `asObservable()` needed? Doesn't `BehaviorSubject` implement the `Observable` interface?

2022-06-13 13:56 UTC, MGibson1 commented on decisions/0003-observable-data-services.md
> +  organizations$: Observable<Organization[]> = this._organizations$.asObservable();
Since we're using typescript it probably isn't strictly necessary, but `asObservable` initializes a new Observable that lacks the `BehaviorSubject` prototype. That means it lacks the methods on the object needed to update the observed value.

Seems a little safer

2022-06-13 14:05 UTC, coroiu commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
I'd suggest looking into maybe also publishing events that enable event sourcing instead of just publishing the latest snapshot of the state. That would enable doing stuff such as popping up messages like `Account name was successfully changed!` by only listening for events, instead of having to compare to previous snapshot or having to manually handle popup events inside the UI component

2022-06-13 14:08 UTC, Hinton commented on decisions/0003-observable-data-services.md
> +  organizations$: Observable<Organization[]> = this._organizations$.asObservable();
Yea, I want to strictly enforce that everything must go through the service, and that it can be the only actor allowed to modify state.

2022-06-13 14:13 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
As in emitting generic events to all the ui components? Sounds eerily similar to `ngrx` which you were not a fan of :).

rxjs has a https://rxjs.dev/api/operators/pairwise operator which can allow you to compare state but that will get a bit messy.

2022-06-13 14:34 UTC, coroiu commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
Noo not at all, NGRX (or actually Redux) doesn't really source events. They might seem similar though and `Action` might look like events, but I think they should be interpreted as a `Command`. Their name make the distinction clearer. 

Redux: ```ChangeAccountNameAction { newName: "someName" }``` 

Events: ``` AccountNameChangedEvent { oldName: "old", newName: "name", [account: <Full Account>] } ```

The flow is also a lot simpler, it really isn't very different from what you've already written.

![image](https://user-images.githubusercontent.com/2285588/173376965-83d72339-41cd-4740-b58d-4d452af088dd.png)

Top is redux, bottom is basically what you wrote but with events instead of state. Note that the events can contain state (though this makes stuff a bit muddier), the important part is that they contain the information about what actually happend and why, instead of just the consequences.

2022-06-13 14:57 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData<T>: (account: string, key: string, options?: StorageOptions) => Promise<void>;
They need to be public though? How else would other services call them.

2022-06-13 15:10 UTC, coroiu commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
Here is an example implementation of what I'm talking about

Superclass Entity
https://github.com/coroiu/corekey-authenticator/blob/92f2f7c6cc55b718d3bb279a36f475711210890b/src/common/ddd/entity.ts

Event creation
https://github.com/coroiu/corekey-authenticator/blob/92f2f7c6cc55b718d3bb279a36f475711210890b/src/modules/crypto/core/account.ts#L101

Event extraction and emitting (this class is very messy, please ignore the mess)
https://github.com/coroiu/corekey-authenticator/blob/92f2f7c6cc55b718d3bb279a36f475711210890b/src/modules/crypto/core/ports/account.service/index.ts#L86

2022-06-13 15:12 UTC, coroiu commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
But it's just a suggestion :D
If it is way to complex for the use case then feel free to ignore me hehe! :shrug:

2022-06-13 15:14 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
It's probably something that merits consideration for a future ADR.

2022-06-13 15:34 UTC, coroiu commented on decisions/0003-observable-data-services.md
> +}
Maybe we have some cases where this could be simplified using the `async` pipe in angular? Or is this only going to be used imperatively within component ts code? Trying to learn a bit about the thoughts behind the Bitwarden codebase

2022-06-14 07:07 UTC, coroiu commented on decisions/0003-observable-data-services.md
> +}
Just noticed the example inside the `example-reactive-data-service` branch, resolving :)

2022-06-14 07:14 UTC, coroiu commented on decisions/0004-refactor-state-service.md
> +    await this._organizations$.next(await this.decryptOrgs(this._activeAccount, organizations));
That's a very good point, it's a completely different thing that has it's own pros and cons, and should be looked at/discussed on it's own! Thanks for considering it! Resolving thread

2022-06-15 18:05 UTC, addisonbeck commented on decisions/0003-observable-data-services.md
> +  }
Have you considered other options for a pattern for unsubscribing from long lived subscriptions? There are more declarative patterns like [using takeUntil](https://www.digitalocean.com/community/tutorials/angular-takeuntil-rxjs-unsubscribe).

2022-06-15 18:11 UTC, addisonbeck commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData: (account: Account, key: string, options?: StorageOptions) => Promise<void>;
Taking this approach makes callers always responsible for knowing what storage location to pull their values from - in addition to the key they need as you mentioned. This can vary across values and across clients, and seems like a downgrade to me. We explicitly decided we _didn't_ want to have to burden callers with that responsibility during the early planning phases for account switching. 

What is keeping state from being managed by the services that own it now (considering 0003 as approved, because it is a necessary step)? They just need observables that keep up with state and update functions that pass through to StateService. 

StateService is a God Class because we use it everywhere, and our State Management needs another abstraction layer. These refactors to StateService don't prevent this - ending the pattern of throwing StateService around to our current services and components does. I don't think these refactors to StateService itself make it any less complicated, but it does make it more difficult to deal with.

2022-06-16 08:11 UTC, Hinton commented on decisions/0003-observable-data-services.md
> +  }
`takeUntil` seems beneficial if you have multiple subscriptions? Or are there any other scenario where it's beneficial? The example mostly serves as a quick reference to how Observables works and is not meant to be the one and only way of doing things.

2022-06-16 08:20 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData: (account: Account, key: string, options?: StorageOptions) => Promise<void>;
I'm not an expert on the `StateService` and would appreciate some insights if I'm wrong!

My thinking is that 0003 will eliminate the need for the `StateService` to keep track of Memory based data. Since we would be moving that responsibility into the different services in the shape of Observables.

That leaves the nuances of `HtmlStorageLocation`. I'm not completely certain how that is used currently but I don't really see much use of the `Session` feature since we will be keeping it in memory through other methods? Would appreciate your insight if there's something I'm missing.

As for my motivations towards simplify the StateService.

1. To avoid state being fetched incorrectly, i.e. outside the expected services. As long as you can fetch say `Organizations` from a different location than `OrganizationService` people might/will do so and therefore avoid safety guards that might exists in `OrganizationService`.
2. Each new feature requires modifications of the `StateService`, this leads to that class having a high change frequency as well as being tightly coupled. We're essentially coupling two or more methods (get/has/save/remove) in the `StateService` to every other service we have.

2022-06-16 15:30 UTC, addisonbeck commented on decisions/0003-observable-data-services.md
> +  }
With the amount of folks working on our projects, do you see any value in having one static pattern for repeated needs as possible? `unsubscribe` works well for one subscription, but breaks down with many. `takeUntil` with an observable stream that completes `onDestory` works well for one subscription and is scalable to more. I think if we _can_ just do it one way, we should, and in this case it's simple.

From another angle, one thing about the `takeUntil` pattern I find valuable, even just for one subscription, is that the subscription is given everything it needs to manage its lifetime upfront. You can follow through to when a subscription will be unsubscribed just by looking at the subscription itself. It's quite explicit, and handy for quickly noting how a subscription gets unsubscribed from.

2022-06-16 16:48 UTC, addisonbeck commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData: (account: Account, key: string, options?: StorageOptions) => Promise<void>;
> My thinking is that 0003 will eliminate the need for the StateService to keep track of Memory based data. Since we would be moving that responsibility into the different services in the shape of Observables.

This is an excellent point, and a benefit to `0003` that I hadn't considered. Most of what the StateService handles is persistent, though. We keep very few bits of data in memory exclusively. 

> don't really see much use of the Session feature since we will be keeping it in memory through other methods?

Moving everything in session storage to memory will cause data to drop when the page is refreshed. In the web vault we make use of both session and local storage for persistent data so the application runs as expected across tabs and refreshes. I don't think we can just move all those session values to memory as the memory values will be cleared on refresh. 

I can't think of a way to escape this problem completely - we need all three locations for the web vault (memory, session, local). I do think we can scope it better, though, and extend our `StateManagementThing` into web for this special case. This is one of the areas of state management as it stands that I find the most frustrating and ugly. 

___

One change we could make that I think would be beneficial to this proposal would be to take another look at the caching functionality that was added to the `StateService` to patch some performance issues we were having with large vault. That could very easily be turned into an observable that sends updates when an account value is saved. We can even handle the web vault's need for session storage this way by overriding whatever method notifies subscribers to merge local and session storage into a single object before sending the update, so both are included and that information is not relevant to any subscribers. Does this make sense?

We would still need to burden callers with knowing where to save an updated account in web's storage service, or abstract that away somehow, but removing memory storage from `StateService` and making `HtmlStorageLocation` scoped to the web vault may make that doable without individual methods per key or a lot of up front work from callers to know where things go.

2022-06-16 18:24 UTC, Hinton commented on decisions/0003-observable-data-services.md
> +  }
I think I agree, having a single pattern will make it more explicit what's going on. I also found https://github.com/cartant/eslint-plugin-rxjs-angular/blob/main/docs/rules/prefer-takeuntil.md which will apply an eslint rule to ensure we clean up after ourselves.

2022-06-22 13:09 UTC, Hinton commented on decisions/0004-refactor-state-service.md
> +  deleteAccountData: (account: Account, key: string, options?: StorageOptions) => Promise<void>;
Sounds like Session Storage is the persistent storage for the web vault in that case? Except for settings. @MGibson1 has been working on a session driven storage implementation, one way to handle different storage implementations are to have the services directly inject whichever storage implementation is needed, i.e. Settings could in web inject the persisted storage, while things like organizations injects the session driven. On desktop both instead injects the persisted storage.

It sounds like we mostly agree but are slightly uncertain exactly how things needs to be implemented. The examples shown in the ADRs are not meant to be the definitive way to implement it, more give an impression on what we would like to achieve.

2022-06-29 22:07 UTC, MGibson1 approved these changes

2022-06-30 15:17 UTC, merged