Add composition ADR
bitwarden/adr pull request #15
Opened 2022-07-21 09:20 UTC by Hinton

Prefer composition over inheritance

2022-07-21 13:37 UTC, MGibson1 requested changes
As is typical I think we need to treat this like a goal document until we're closer to this ideal.

Do you have an example component that is doing this well? Should we link some recent change as an example of stepping in this direction?

2022-07-21 13:37 UTC, MGibson1 commented on decisions/0009-angular-composition-over-inheritance.md
> +has also lead to tight coupling, difficulty in understanding the impact a change will have. It also
```suggestion
has also lead to tight coupling and therefore difficulty in understanding the impact a change will have. It also
```

2022-07-21 15:30 UTC, Hinton commented
I have examples on how to not do it 😁. No but I'll try and find some good examples.

2022-07-21 15:44 UTC, MGibson1 commented
Right, unfortunately right now we have almost exclusively anti-examples. I think we need a way to call that out in this (and probably other) ADRs.

Some kind of status like `In Progress` or `Standard in Code` that tells you if you can trust patterns you find in repositories we host

2022-07-22 15:54 UTC, MGibson1 approved these changes
I want to get this into ratification to encourage improvement, but I think there's still an opportunity for examples and help links on how to progress from our current state to a `standard` status.

2022-07-25 09:18 UTC, merged