Angular NgModules
bitwarden/adr pull request #16
Opened 2022-07-21 09:25 UTC by Hinton

Based on #6.

2022-07-21 09:30 UTC, Hinton commented on decisions/0010-angular-ngmodules.md
> +- [Barrel Files](https://dev.to/luispa/how-to-create-barrels-in-typescript-or-javascript-59ma)
Angular NgModules do not provide the same functionality as barrel files. Barrel files limits the public API as covered by https://github.com/bitwarden/adr/blob/master/decisions/0002-public-module-npm-packages.md.

2022-07-21 09:30 UTC, Hinton commented on decisions/0010-angular-ngmodules.md
> +It demonstrates a couple of useful features of NgModules.
I don't quite understand why the vault filters are a good example. It exports two different domains, individual and organizations which makes it a bad candidate to be imported in any scope. It also provides it's own service which is something you need to be careful with since if that module is only lazy loaded it will instantiate multiple instances of the service while we expect it to be a singleton.

2022-07-21 13:52 UTC, MGibson1 requested changes

2022-07-21 13:52 UTC, MGibson1 commented on decisions/0010-angular-ngmodules.md
> +- Consider creating a `FeatureShared` module in case additional functionality needs to be shared
`SharedFeature` and `FeatureShared` are too similar in name to be introduced here without a proper definition.

I suggest an extra
```markdown
## Implementation
```
section that defines these things and gives guidelines on how to split up a feature with shared functionality

2022-07-22 14:43 UTC, addisonbeck commented on decisions/0010-angular-ngmodules.md
> +- [Barrel Files](https://dev.to/luispa/how-to-create-barrels-in-typescript-or-javascript-59ma)
NgModules also limit the public API of a structure via declarations and exports.

2022-07-22 14:47 UTC, addisonbeck commented on decisions/0010-angular-ngmodules.md
> +It demonstrates a couple of useful features of NgModules.
I agree on both points, the scoping and the service. Both of those issues are addressed on #17 and I don't think they are relevant when determining if NgModules have merit on their own. VaultFiltersModule is still a good example of the flexibility and benefit of NgModules, even if it's not still a good example of how we will implement them (which it will be again soon).

2022-07-22 14:51 UTC, addisonbeck commented on decisions/0010-angular-ngmodules.md
> +- Consider creating a `FeatureShared` module in case additional functionality needs to be shared
I think this makes more sense now with the update to read as `feature/shared`. There won't be a module called `FeatureSharedModule`. There will just be a `src/app/shared` and maybe a `src/app/feature/shared` for scoped logic to a feature.

2022-07-22 14:53 UTC, addisonbeck commented
I think this one looks great Oscar, thanks again.

2022-07-25 14:48 UTC, MGibson1 approved these changes

2022-07-25 14:49 UTC, merged