Move Request and Responses to live next to their services
bitwarden/adr pull request #24
Opened 2022-08-25 16:22 UTC by Hinton

2022-08-29 17:34 UTC, MGibson1 reviewed
Are you suggesting doing this for all, for example, folder models or just the api request/response.

I think we're ready for this from an api standpoint, but not in terms of export and persistence perpectives.

I would like to limit this ADR to API only unless you disagree

2022-08-29 18:27 UTC, Hinton commented
I did change it to request and responses only, but it might be slightly unclear. I'll revisit it.

2022-09-12 19:20 UTC, MGibson1 requested changes

2022-09-12 19:20 UTC, MGibson1 commented on decisions/0013-avoid-layered-folder-structure.md
> +And any model defined in the service in the service directory. Abstractions are part of the service
defined seems like the wrong word, since they're technically defined in the file you're moving.

Let's change to _used_, then I think we're good

2022-09-26 19:37 UTC, MGibson1 approved these changes

2022-09-27 13:41 UTC, merged