Strict typescript
bitwarden/adr pull request #26
Opened 2022-09-02 10:34 UTC by Hinton

2022-09-07 17:25 UTC, MGibson1 requested changes
Like it in general, but a few comments

2022-09-07 17:25 UTC, MGibson1 commented on decisions/0014-typescript-strict.md
> +of a priority that it's worth raising this topic again.
Not sure what the purpose of this line is

2022-09-07 17:25 UTC, MGibson1 commented on decisions/0014-typescript-strict.md
> +adding new non-strict files in the category that we are currently migrating.
Not sure I agree with this, Are you worried people will not know how to adhere to strict types?

2022-09-08 08:52 UTC, Hinton commented on decisions/0014-typescript-strict.md
> +of a priority that it's worth raising this topic again.
Removed.

2022-09-08 08:54 UTC, Hinton commented on decisions/0014-typescript-strict.md
> +adding new non-strict files in the category that we are currently migrating.
Yes per our discussions before. It's also going to be difficult to use strict when you depend on non-strict files.

2022-09-08 17:51 UTC, MGibson1 commented on decisions/0014-typescript-strict.md
> +adding new non-strict files in the category that we are currently migrating.
but I'd like to imply a best effort should be done. What do you think about 
```suggestion
a proper example how how they should be migrated. And during the initial migration period a best effort should be made to be strict-compliant, but we should
not prevent people from adding new files that are not strict. What we should prevent is people
adding new non-strict files in the category that we are currently migrating.
```

2022-09-08 19:52 UTC, Hinton commented on decisions/0014-typescript-strict.md
> +adding new non-strict files in the category that we are currently migrating.
Seems good.

2022-09-21 15:29 UTC, MGibson1 approved these changes

2022-09-26 10:26 UTC, merged